# Set the current review czar
# (This must refer to the Github value of the assignee)
czar: lorelei-sakai

# Set the backup czar for pull requests authored by czar
# (This must refer to the Github value of the assignee)
backup: C2Redhat

# Triage assignment reference
triage: msakai
triage-next: cchung

# A list of possible triage, review czar and backup assignees
members:
  awalsh:
    Role: advisory
    Github: rhawalsh
    Jira: awalsh1
  bjohnsto:
    Role: rotation
    Jira: bjohnsto
    Github: bjohnsto
  cchung:
    Role: rotation
    Jira: cchung
    Github: C2Redhat
  raeburn:
    Role: rotation
    Jira: raeburn
    Github: raeburn
  msakai:
    Role: advisory
    Github: lorelei-sakai
    Jira: msakai

# Upcoming rotation:
# If running on the first date listed below, the following command will generate the new appropriate dates:
#   count=0; i=14; while [ $count -lt 8 ]; do date -d "+${i}days" +"%d-%b"; i=$((i+14)); count=$((count+1)); done
# Date   | triage/czar | backup
# -------+-------------+----------
# 21-Jul | cchung      | raeburn
# 04-Aug | raeburn     | msakai
# 18-Aug | msakai      | cchung
# 01-Sep | cchung      | raeburn
# 15-Sep | raeburn     | msakai
# 29-Sep | msakai      | cchung
# 13-Oct | cchung      | raeburn
# 27-Oct | raeburn     | msakai
